esx-framework/esx_core

- [esx]/es_extended/server/functions.lua
This addresses the original issue on v1-Final where whilst there was async updates being done, the async list of tasks to run only had a single task anyway so all update statements were still being done one by one. I thought my take on the solution might still be of value on the legacy branch. Rather the run a stack of UPDATE statements which still requires multiple calls across process to MySQL/MariaDB and potentially across the wire if they're not on the same server, then just do a single UPDATE statement for everyone in one step. This is achieved as a set operation across UNIONed SELECT statements representing the value of each column being updated for each player. I've used this approach a couple of times in ESX resources and thread hitches stopped. This level of efficiency takes …
> Optimised player save data function

- README.md
- [esx]/es_extended/README.md
- [esx]/es_extended/client/functions.lua
- [esx]/es_extended/server/functions.lua
- [esx_addons]/esx_garage/client/main.lua
* Print the number of players saved and the time taken to save all players
* Check if xPlayers exist before defining variables
* Wait for MySQL.Async response before triggering callback
* Reduced the sleep on ESX.TimeoutCallbacks
* Interior garage markers will be drawn correctly
* Properly set the vehicle engine state after entering or leaving a garage
* Some minor optimisations to distance and vehicle checks
> improvement & fix(esx & garage): Changes to new saveplayers function; draw garage markers correctly

- [esx_addons]/esx_holdup/client/main.lua
- [esx_addons]/esx_holdup/config.lua
- [esx_addons]/esx_holdup/server/main.lua
Optimized performance and fix bug when the robbery has been canceled, player still could receive money from the robbery.
> [esx_holdup] Optimized and fixed bug when the robbery has been canceled.

- README.md
- [esx]/es_extended/README.md
- [esx]/es_extended/client/functions.lua
- [esx]/es_extended/server/common.lua
- [esx]/es_extended/server/functions.lua
- [esx]/es_extended/server/paycheck.lua
- [esx_addons]/esx_status/server/main.lua
- esx_example/README.md
- esx_example/client/main.lua
- esx_example/server/main.lua
- server.cfg
- Resolved issue with ESX.Game.GetPeds
- Allow string and hash for ESX.Game.SpawnObject
- Ensure player has a status before saving it
- Added resources to server.cfg
- Added some more information to esx_example
- Replaced recursive functions from ESX (saveplayers and paychecks) with loops
> fixes: Fix major issue with ESX client function, minor fixes for ESX and status

- [esx]/es_extended/server/common.lua
FML 3 months for this to get reported
> fix(esx): Loop SavePlayers as intended

- [SQL]/legacy.sql
Add non-existent whitelist table in sql file
> Fix non-existent whitelist table in sql file

- [esx_addons]/esx_drugs/config.lua
just add marker durgshop config for path NRTnarathip
> Update: esx_drugs add marker config

- [esx_addons]/esx_drugs/client/main.lua
Optimize, Add feture marker zone drugshop, Fixed the issue of pressing open menu not working when press key backspace for cancel ui
> Fix Bug: game crash when player in zone drugshop

- [esx_addons]/esx_dmvschool/client/main.lua
change vector3 - var type table
to vector3 - vector3
and Config.DrawDistance it never using
just add implement the "config DrawDistance"
> Fix Error: esx_dmvschool arithmetic operator

- [esx]/es_extended/locales/br.lua
- [esx]/es_extended/locales/cs.lua
- [esx]/es_extended/locales/de.lua
- [esx]/es_extended/locales/en.lua
- [esx]/es_extended/locales/es.lua
- [esx]/es_extended/locales/fi.lua
- [esx]/es_extended/locales/fr.lua
- [esx]/es_extended/locales/pl.lua
- [esx]/es_extended/locales/sc.lua
- [esx]/es_extended/locales/sv.lua
- [esx]/es_extended/locales/tc.lua
> fix(locales): update invalid command to fit notifications

- [esx]/es_extended/server/main.lua
Integration for esx_multicharacter, groups consistency between characters.
> feat: use first char group for new chars

- [esx_addons]/esx_ambulancejob/server/main.lua
The variable type of "isDead" is a boolean, not a number.
> Fix Bug isDead == 1 it be should isDead == true

- [esx_addons]/esx_taxijob/client/main.lua
from vector3 - table coords
to vector3 - vector3
> FixBug: taxijob vector3 - table coords

- [esx]/es_extended/server/main.lua
- [esx_addons]/esx_policejob/client/main.lua
@thelindat and I talked about this and I'd like to revert the groups commit because it may break multicharacter; we will handle it differently in the future. Also fixes an issue with searching players in esx_policejob.
> Patch: remove groups change + fix openInventory issue

- [esx_addons]/esx_garage/server/main.lua
Fixed Garages so it works somewhat
> Fix Garages

- [esx_addons]/esx_ambulancejob/client/main.lua
> Corrected few words

- [esx_addons]/esx_joblisting/fxmanifest.lua
- [esx_addons]/esx_joblisting/server/main.lua
Fixed joblisting not showing any jobs
> Fixed esx_joblisting

- [esx_addons]/esx_optionalneeds/esx_optionalneeds.sql
esx_optionalneeds tries to insert data in a table that doesn't exist in esx_shops
References:
https://github.com/esx-framework/esx-legacy/pull/206
https://github.com/esx-framework/esx-legacy/pull/207
> Remove useless inesert in esx_optionalneeds 

- [esx]/es_extended/client/functions.lua
Add RGB support and fixed liveries
> Feat(es_extended/client/functions.lua): Add RGB saving to vehicles

- [esx]/esx_menu_default/html/css/app.css
- [esx]/esx_menu_dialog/html/css/app.css
completely rewrote the front-end design of the ESX Menus to look more cleaner.
> feat(ESX Menus): new menus

- [esx]/esx_menu_default/html/css/app.css
Fixed the font not working because of a mistype and darker color for the menu.
> fix(ESX Menus): Fixed font + darker color

- [esx]/esx_multicharacter/server/main.lua
Stopping the resource from starting properly.
> Random ) in server/main.lua

- [esx_addons]/esx_lscustom/client/main.lua
Change the position of the condition GetVehicleClass (not working before and working now)
> Fix - LS Custom wheels changement on bikes

- [esx]/esx_multicharacter/client/main.lua
> fix female model

- [esx]/es_extended/server/commands.lua
- [esx]/es_extended/server/functions.lua
functions.lua - A small fix to not give an error in the console when the called item does not exist.
commands.lua - Calling GetPlayerPed more lightly
> tweak(es_Extended/server/functions.lua): warn when an unregisted item is used

- [esx]/esx_menu_default/html/css/app.css
fixed the positioning for top-right because it wasen't the same as top-left xD
Preview:
https://imgur.com/a/mGJdrLB
> fixed the positioning for top-right

- [esx]/esx_notify/nui/css/style.css
- [esx]/esx_notify/nui/index.html
- [esx]/esx_notify/nui/js/script.js
Added ProgressBar to esx notify
- the ProgressBar shows the timeout for when the notification is going to disappear
https://imgur.com/nKda41I
> refactor(esx_notify)

- [esx]/esx_progressbar/readme.md
Also changed a bit of the formatting to make it a bit easier to read for the average joe. They both should work just fine at least I can confirm the export only.
> fix(esx_progressbar): Fixed missing })

- [esx]/es_extended/server/functions.lua
Overriding command colors whole console.
https://cdn.upload.systems/uploads/k7TZJpqn.png
> fix(es_extended): Overriding command colors console.

- [esx]/es_extended/client/functions.lua
- [esx]/es_extended/client/main.lua
- [esx]/esx_progressbar/Progress.lua
- [esx_addons]/esx_ambulancejob/client/job.lua
- [esx_addons]/esx_ambulancejob/client/main.lua
- [esx_addons]/esx_animations/client/main.lua
- [esx_addons]/esx_basicneeds/client/main.lua
- [esx_addons]/esx_policejob/client/main.lua
After playing the animation, it is good to remove the anim dict. Why ? Because it is no longer used.
> tweak(ESX): Added RemoveAnimDict after TaskPlayAnim

- [SQL]/legacy.sql
changed because why are ther chars it should be null.
> feat(sql): SQL Issue

- [esx_addons]/esx_ambulancejob/locales/es.lua
Removed some extra spacings, added amount of money to respawn_bleedout_fine_msg and corrected respawn key in distress_send
> fix(locales) esx_ambulancejob spanish translation file

- [esx]/esx_multicharacter/client/main.lua
skin.sex = 0 -> male
skin.sex = 1 -> female
> fix(multicharacter): ped gender

- [esx_addons]/esx_clotheshop/locales/es.lua
A missing line has been translated
> fix(spanish locales) esx_clotheshop translation file

- [esx]/esx_menu_default/html/css/app.css
- Fixed menu centering;
- Cleaned up the css a bit "multiple mistakes";
- Yall wrote text-allign instead of "text-align"
Proof everything works: [link](https://imgur.com/a/078okFc)
> refactor(esx_menu_default)

- [esx]/esx_textui/TextUI.lua
- [esx]/esx_textui/nui/css/style.css
- [esx]/esx_textui/nui/index.html
- [esx]/esx_textui/nui/js/script.js
**Update ESX Textui**
- Replaced font awesome icons with google icons
- Color text now works fine
- Old ui hides automaticly when a new one is requested
- Got rid of jquery
- Added debug commands "enable lua line 1"
Have fun :)
Preview: 
https://user-images.githubusercontent.com/80540494/177545685-deb0b9c4-dbae-400c-a748-5ea7509ce9aa.mp4
> refactor(esx_textui)

- [esx]/es_extended/locales/es.lua
Added missing translations for bring, goto, freeze, kill and duty commands
> fix(es_extended/locales/es.lua): Add missing translations

- [esx_addons]/esx_boat/config.lua
Export for getting boat garage zones,
> feat(boat/config): exports getting boat garages

- [esx_addons]/esx_garage/config.lua
Exports for getting the location of garages and impounds.
> exports for getting garages and impound locations

- [esx]/es_extended/server/functions.lua
Should have tested it beforehand.
> Fucked up the validate registercommand logic (Did it the wrong way around)

- [esx_addons]/esx_cruisecontrol/locales/it.lua
- [esx_addons]/esx_holdup/it.lua
create Italian language translations for esx_holdup & esx_cruisecontrol
> feat(Italian language for esx_holdup & esx_cruisecontrol)

- [esx_addons]/esx_banking/client/main.lua
- [esx_addons]/esx_banking/html/config.json
- [esx_addons]/esx_banking/html/css/app.css
- [esx_addons]/esx_banking/html/scripts/app.js
- [esx_addons]/esx_banking/locales/en.lua
- [esx_addons]/esx_banking/locales/hu.lua
- [esx_addons]/esx_banking/locales/it.lua
- readme.md
Hi! 
I fixed some issue this in pr.
- Fixed responsive table small resolution
- Fixed translate issues
- Fixed timezone set issue
Please merge this commit! @Benzo00
> fix(esx_banking) some issue fix and responsive table fix

- [esx_addons]/esx_property/client/cctv.lua
- [esx_addons]/esx_property/locales/en.lua
Notification for CCTV Screenshot
> feat(esx_property) CCTV Screenshot Translation

- [esx_addons]/esx_basicneeds/config.lua
- [esx_addons]/esx_basicneeds/locales/br.lua
- [esx_addons]/esx_basicneeds/locales/en.lua
- [esx_addons]/esx_basicneeds/server/main.lua
better basicneeds, create items in the config instead of copy and pasting the same code for a lot of items.
> refactor:(better esx basicneeds)

- [esx_addons]/esx_drugs/locales/nl.lua
dutch lang support for esx_drugs.
> refactor:(esx_drugs) - Dutch translation 

- [esx]/es_extended/client/main.lua
> fix:(es_extended) - typo

- [esx_addons]/esx_society/client/main.lua
```lua
RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(xPlayer)
ESX.PlayerData = xPlayer
ESX.PlayerLoaded = true
RefreshBussHUD()
end)
```
Is there already
> remove(playerload/function): duplicate

- [esx_addons]/esx_property/client/main.lua
- [esx_addons]/esx_property/locales/en.lua
added translations to "client/main.lua" up to line 1113
> feat(esx_property) translations

- [esx_addons]/esx_addonaccount/server/classes/addonaccount.lua
Trigger this serverside as well to help with syncing
> feat: events for when updating esx_society accounts

- [esx]/es_extended/server/classes/player.lua
little fix for set money logic
> fix(es_extended): setAccountMoney logic fix

- [esx_addons]/esx_society/client/main.lua
Small refactoring to remove these **elements[#elements+1]**
> refactor(esx_society/client/main.lua): now using table.insert()

- [esx]/es_extended/server/classes/player.lua
otherwise it doesn't update correctly and after relogging you lose ammo if weapon was reloaded at least once
✅ tested, that worked for me.
> fix(es_extended): ammo saving

- [esx]/esx_identity/html/index.html
Removed unused onKeyDown tag from inputs in form.
According to @Mycroft-Studios the validation is done in the lua part so might as well remove them.
> fix(esx_identity/html): Syntax error on registration

- [esx_addons]/esx_clotheshop/client/main.lua
When arms are changed with arms_2 bigger than 0, arms becomes invisible until arms_2 is changed. Added arms_2 to restricted menu
> fix(esx_clotheshop/client/main.lua) Invisible arms

- [esx]/es_extended/client/modules/death.lua
when player drop from falling and die function not active
> Fix (es_extended): player death event

- [esx_addons]/esx_billing/client/main.lua
- [esx_addons]/esx_dmvschool/client/main.lua
- [esx_addons]/esx_taxijob/client/main.lua
Going to add more scripts here with context implementation.
> context implementation

- [esx]/es_extended/server/classes/player.lua
when getting xPlayer and using the coords it would not show me the heading of the player always 0.0 so I fixed it
> xPlayer.coords.heading fixed

- [esx_addons]/esx_lscustom/client/main.lua
- [esx_addons]/esx_lscustom/server/main.lua
1. sleeper loop fix
2. players count fix
> fix(esx_lscustom): fixes loop and players count

- [esx_addons]/esx_weaponshop/locales/et.lua
> feat(esx_weaponshop) - et translation

- [esx_addons]/esx_shops/locales/et.lua
> feat(esx_shops) - et translation

- [esx_addons]/esx_rpchat/locales/et.lua
> feat(esx_rpchat) - et translation

- [esx_addons]/esx_joblisting/locales/et.lua
> feat(esx_joblisting) - et transaltion

- [esx_addons]/esx_holdup/locales/et.lua
> feat(esx_holdup) - et transaltion

- [esx_addons]/esx_drugs/locales/et.lua
Estonian translation for the resource.
> feat(esx_drugs) - et transaltion

- [esx_addons]/esx_clotheshop/locales/et.lua
> feat(esx_clotheshop) - et transaltion

- [esx_addons]/esx_boat/locales/et.lua
> feat(esx_boat) - et transaltion

- [esx_addons]/esx_billing/locales/et.lua
> feat(esx_billing) - et translation

- [esx_addons]/esx_basicneeds/locales/et.lua
> feat(esx_basicneeds) - et translation

- [esx_addons]/esx_barbershop/locales/et.lua
> feat(esx_barbershop) - et translation

- [esx_addons]/esx_banking/locales/et.lua
> feat(esx_banking) - et translation

- [esx_addons]/esx_bankerjob/locales/et.lua
> feat(esx_bankerjob) - et translation

- [esx_addons]/esx_allowlist/locales/et.lua
> feat(esx_allowlist) - et translation

- [esx_addons]/esx_property/server/main.lua
> fix GetPlayerProperties 

- [esx_addons]/esx_banking/README.md
- [esx_addons]/esx_banking/html/config.json
- [esx_addons]/esx_banking/html/scripts/app.js
- [esx_addons]/esx_banking/server/main.lua
fix(esx_banking/html/scripts/app.js): translate undefined fix
feat(esx_banking/server/main.lua): add new logtransaction export in server side
> fix(esx_banking)

- [esx_addons]/esx_license/config.lua
- [esx_addons]/esx_license/fxmanifest.lua
- [esx_addons]/esx_license/server/main.lua
Add license validationg function for add . ( detect lua executor cheat )
Add job allow list to remove license from player.
> refactor(esx_license): rework license resource

- [esx_addons]/esx_lscustom/locales/es.lua
> Last update in spanish

- [esx]/es_extended/server/classes/player.lua
pretty sure i have done this fix earlier, but someone tend to undo fixes and revert to broken code over and over again
> fix(es_extended): allow set account to 0 too

- [esx_addons]/esx_banking/client/main.lua
- [esx_addons]/esx_banking/server/main.lua
> fix(esx_banking): issue #736

- [esx]/es_extended/client/functions.lua
> fix(es_extended/client/functions.lua): setVehicleProps

- [esx]/es_extended/common/functions.lua
this method remove for loops, and small optimalize code
> refactor: es_extended weapon functions

- [esx]/es_extended/server/main.lua
- [esx_addons]/esx_allowlist/server/main.lua
* adding prefix where it rejects players connection
> refactor(): adding ESX Prefix

- [esx_addons]/esx_banking/html/config.json
> translation

- [esx]/esx_multicharacter/html/locales/es.js
- [esx_addons]/esx_property/server/main.lua
> Fix Translate Saving

- [esx]/es_extended/client/functions.lua
> fix(es_extended): default inventory showing

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
> Add Feature Request and General Support

- [core]/es_extended/client/main.lua
Thanks Tinky124 for inspiration in DisableVehicleRewards
> Fix Thread for "optional" features and little optimalization

- [core]/esx_context/main.lua
> fix(esx_context/main.lua): nui callback warning

- [core]/es_extended/client/functions.lua
This adds the ability to save interior/dashboard color to the vehicle properties, as well as applying it to the vehicle.
> feat(client/functions): Interior/Dashboard saving/application

- [core]/es_extended/config.lua
- [core]/es_extended/server/common.lua
Add Config.EnablePaycheck option
> feat(es_extended/config.lua): Config.EnablePaycheck option

- [core]/es_extended/client/functions.lua
- [core]/es_extended/client/main.lua
- [core]/es_extended/client/modules/callback.lua
- [core]/es_extended/fxmanifest.lua
- [core]/es_extended/server/common.lua
- [core]/es_extended/server/functions.lua
- [core]/es_extended/server/modules/callback.lua
- ESX.RegisterClientCallback, ESX.TriggerClientCallback
- ESX.GetVehicleType *(client)*
Server side ESX.GetVehicleType has been optimized
> feat(es_extended): callback functions, vehicle type

- [core]/es_extended/client/functions.lua
- [core]/es_extended/server/functions.lua
- [core]/esx_context/main.lua
- [core]/esx_menu_list/client/main.lua
- [core]/esx_multicharacter/client/main.lua
- [core]/esx_multicharacter/server/main.lua
> refactor: more logical code

- [core]/esx_multicharacter/html/locales/nl.js
> chore(esx_multicharacter): Update Dutch(nl) locales

- [core]/esx_multicharacter/readme.md
it had the old UI as well as bad english.
> Tweak(esx_multicharacter): update Readme

- [core]/es_extended/html/js/wrapper.js
- [core]/es_extended/locale.js
- [core]/esx_context/index.html
- [core]/esx_identity/html/index.html
- [core]/esx_menu_default/html/js/app.js
- [core]/esx_menu_dialog/html/js/app.js
- [core]/esx_menu_list/html/js/app.js
optimization is explained by this article:  https://www.builder.io/blog/double-equal-vs-triple-equal
> refactor: slight optimization

- [core]/es_extended/server/functions.lua
> :pencil2: fix typo change Config to Core

- [core]/esx_progressbar/Progress.lua
Personally, I think this feature should have been here a long time ago. I hope that adding this code will help players in the future and if anyone here has a suggestion for a code change feel free to comment.
> Added option to externally cancel progress bar

- [core]/es_extended/client/functions.lua
Integrate them into the VehicleProperties Functions, and make sure that they return true on the check so there should be no problems with older builds.
Thx to mycroft for the idea with the type <3
> Add Support for Drift Tyres

- [core]/es_extended/server/classes/player.lua
getMeta no longer prints an error message on the index did not exist condition.
> refactor(xPlayer): delete getMeta error message

- [core]/es_extended/server/main.lua
to spawn vehicles client side using a callback to server side spawn vehicles 👍
> add esx:spawnVehicle callback

- [core]/es_extended/server/functions.lua
#1087 The problem needs to be fixed at the root level.
> :pencil2: fix(es_extended/functions.lua) handle args.playerId is nil

- [core]/es_extended/server/classes/overrides/oxinventory.lua
> Fix oxinventory.lua (es_extended/server/classes/overrides/oxinventory.lua

- [core]/es_extended/client/functions.lua
- [core]/es_extended/client/main.lua
> fix(esx_core/main.lua, function.lua)

- readme.md
> tweak(readme): general changes

- [core]/esx_multicharacter/client/main.lua
Make the spawn transition smoother
> refactor(esx_multicharacter/client): Smoother spawn transition

- [core]/es_extended/server/commands.lua
Setjob logs were not working/false
> fixed setjob logs

- [core]/es_extended/client/main.lua
I tested to verify that everything works correctly after the modification I made and everything is good
> Fix : The noclip currently uses only part of the locales

- .github/workflows/main.yml
- [core]/es_extended/server/classes/player.lua
> Handle setMeta subvalue

- [core]/cron/README.md
- [core]/esx_context/README.md
- [core]/esx_loadingscreen/README.md
- [core]/esx_menu_default/README.md
- [core]/esx_notify/readme.md
- [core]/esx_textui/readme.md
- [core]/skinchanger/README.md
updated the documentation urls
> updated README files

- [core]/es_extended/client/main.lua
- [core]/es_extended/server/functions.lua
- [core]/es_extended/server/main.lua
[#7](https://github.com/esx-framework/esx_status/issues/7) feature request
📦  save health and armour in the metadata, and load the metadata when the player joins
> :package: Add new feature save hp and armor in metadata

- [core]/es_extended/server/commands.lua
> 🚑 Handle nil values if use command in server console

- [core]/es_extended/server/commands.lua
- [core]/es_extended/server/functions.lua
Commit: https://github.com/esx-framework/esx_core/commit/5e44373d80c3eb94bad3b068788f5c742adb3e30
Context: #1151
> :boom: Fix breaking change

- [core]/esx_identity/client/main.lua
> 🚑 Fix esx identity nui cursor bug

- [core]/es_extended/server/classes/player.lua
- [core]/es_extended/server/common.lua
- [core]/es_extended/server/functions.lua
- [core]/es_extended/server/main.lua
- Handle job counter with GlobalState
- Little JobsPlayerCount refactor
> :recycle: Little refactor and handle job counter with GlobalState

- [core]/es_extended/server/commands.lua
> :ambulance: Fix server commands in server console

- [core]/es_extended/locales/fi.lua
> Updated fi.lua

- [core]/es_extended/server/functions.lua
Reverts esx-framework/esx_core#1281
> Revert "Added ESX.DeleteJob for Runtime"

- [core]/es_extended/client/main.lua
> hotfix(es_extended/client/main.lua):reinitiating backwards compatibility with spawnmanager

- [core]/es_extended/config.lua
Corrected some spelling errors.
> fix(es_extended/config.lua): Fix Typo Errors

- [core]/es_extended/client/functions.lua
i replaced, where the functionality of pairs loops where not needed, these with regular for loops as there perform better
> perf/refactor(client/functions): replace pairs loops with for loops where possible

- [core]/es_extended/client/functions.lua
Refactored the code to determine the burst tyres of an vehicle
was already discussed in https://github.com/esx-framework/esx_core/pull/1327
@Gellipapa
> refactor(client/functions): refactor getting burst tyres on vehicle

- [core]/es_extended/server/classes/player.lua
since it was removed, I added it again, which I did already in the past but somehow you missed the heading again
> added heading again for xPlayer.getCoords()

- [core]/es_extended/common/modules/math.lua
- [core]/es_extended/server/main.lua
- [core]/esx_multicharacter/client/main.lua
Fixed: https://github.com/esx-framework/esx_core/issues/1345
> :ambulance: Fix random default spawn coords

- [core]/es_extended/client/main.lua
- [core]/es_extended/imports.lua
- [core]/es_extended/locale.lua
- [core]/es_extended/server/main.lua
- [core]/esx_context/main.lua
- [core]/esx_multicharacter/client/main.lua
- [core]/esx_skin/client/main.lua
> :wrench: Fix lint errors

- [core]/cron/fxmanifest.lua
- [core]/es_extended/fxmanifest.lua
- [core]/es_extended/server/classes/player.lua
- [core]/esx_context/fxmanifest.lua
- [core]/esx_identity/fxmanifest.lua
- [core]/esx_loadingscreen/fxmanifest.lua
- [core]/esx_menu_default/fxmanifest.lua
- [core]/esx_menu_dialog/fxmanifest.lua
- [core]/esx_menu_list/fxmanifest.lua
- [core]/esx_multicharacter/fxmanifest.lua
- [core]/esx_notify/fxmanifest.lua
- [core]/esx_progressbar/fxmanifest.lua
- [core]/esx_skin/fxmanifest.lua
- [core]/esx_textui/fxmanifest.lua
- [core]/skinchanger/fxmanifest.lua
> 📦 Hotfix 1.10.7

- [core]/es_extended/server/classes/player.lua
Currently the docs say:`Money` and `Bank`, This will currently cause an error when used, better to accept both than change the docs
> tweak(Server/Classes/Player) Lowercase account check

- [core]/es_extended/locales/de.lua
> fix(es_extended/locales/de.lua): fixed translation

- [core]/es_extended/server/main.lua
> :ambulance: Fix player data name value

- [core]/es_extended/client/main.lua
> :package: disabled police scanner sound

- [core]/es_extended/client/functions.lua
Small fixes for bugs appeared in the last update
> fix(es_extended/client/functions.lua): Fix typos

- [core]/es_extended/config.lua
- [core]/es_extended/server/classes/player.lua
- [core]/es_extended/server/commands.lua
Reverts esx-framework/esx_core#1432
> Revert "Add job duty"

- [core]/es_extended/server/main.lua
return if target has no weapon
> fix(es_extended/server/main.lua): return if no weapon

- [core]/cron/server/main.lua
This PR addresses issue [#1294](https://github.com/esx-framework/esx_core/issues/1294) in hopes to help identify and resolve the reported bug.
---
- **Improved Code Clarity**
- Renamed variables for better contextual understanding.
- **Added Type Annotations**
- **Enhanced Validation**
- Added assertions in the `cron:runAt` event handler to validate input parameters (`h`, `m`, `cb`).
- Included resource-specific error messages using `GetInvokingResource`.
> refactor(cron/server/main)

- [core]/skinchanger/client/main.lua
> fix(skinchanger): wrong operator

- [core]/es_extended/client/modules/actions.lua
- [core]/skinchanger/client/main.lua
- This hotfix merges three critical PRs from the `dev` branch into `main` to address urgent issues.
- The following PRs have been cherry-picked:
- [PR #1](https://github.com/esx-framework/esx_core/pull/1475)
- [PR #2](https://github.com/esx-framework/esx_core/pull/1478)
- [PR #3](https://github.com/esx-framework/esx_core/pull/1469)
These changes are intended to resolve issues in the current release and ensure stability on `main` until the next full release.
> 1.11.2 Hotfix

- [core]/es_extended/client/main.lua
- [core]/es_extended/client/modules/npwd.lua
- [core]/es_extended/imports.lua
- [core]/esx_multicharacter/client/main.lua
- [core]/esx_skin/client/main.lua
PRs: 
https://github.com/esx-framework/esx_core/pull/1484
https://github.com/esx-framework/esx_core/pull/1480
> chore(esx_core): add 2 pull request changes

- [core]/es_extended/server/modules/actions.lua
> refactor(es_extended/server/modules/actions): replace deprecated RegisterServerEvent

- [core]/es_extended/server/functions.lua
- [core]/es_extended/shared/modules/table.lua
- Added `ESX.Table.ToArray` util function
- Refactored `ESX.GetExtendedPlayers`
> refactor(es_extended/server/functions): refactor ESX.GetExtendedPlayers

- [core]/es_extended/client/functions.lua
- [core]/es_extended/client/main.lua
- [core]/es_extended/shared/config/main.lua
- [core]/es_extended/shared/functions.lua
- [core]/esx_multicharacter/client/modules/multicharacter.lua
- [core]/esx_multicharacter/server/modules/multicharacter.lua
- [core]/esx_skin/client/modules/menu.lua
- [core]/skinchanger/config.lua
Merges the following PRs into main as a hotifx.
- https://github.com/esx-framework/esx_core/pull/1504
- https://github.com/esx-framework/esx_core/pull/1508
- https://github.com/esx-framework/esx_core/pull/1510
- https://github.com/esx-framework/esx_core/pull/1511
- https://github.com/esx-framework/esx_core/pull/1509
> 1.11.3 Hotfix

- [core]/es_extended/server/functions.lua
Reverts esx-framework/esx_core#1548
> Revert "fix(es_extended/server/functions): Core.IsPlayerAdmin returning false"

- [core]/es_extended/server/bridge/inventory/oxinventory.lua
- [core]/es_extended/server/classes/player.lua
- [core]/es_extended/server/common.lua
- [core]/es_extended/server/functions.lua
- [core]/es_extended/server/main.lua
- [core]/es_extended/server/modules/createJob.lua
- [core]/es_extended/server/modules/npwd.lua
- [core]/es_extended/server/modules/onesync.lua
- [core]/es_extended/server/modules/paycheck.lua
- [core]/esx_multicharacter/server/modules/database.lua
- [core]/esx_multicharacter/server/modules/functions.lua
Moved a bunch of stuff that should not be exposed from the ESX object into the core object. Technically, this should not be considered a breaking change, unless people have been misusing the ESX object.
---
> reafactor!(es_extended): Cleanup ESX object

- [core]/es_extended/locales/en.lua
- [core]/es_extended/shared/config/weapons.lua
Added missing chop shop dlc weapons
- WEAPON_BATTLERIFLE
- WEAPON_SNOWLAUNCHER
- WEAPON_HACKINGDEVICE
> feat(es_extended/shared/config/weapons): add chop shop dlcs weapons

- [core]/es_extended/locales/en.lua
- [core]/es_extended/shared/config/weapons.lua
Added missing bottom dollar bounties dlc weapon
- WEAPON_STUNROD
> feat(es_extended/shared/config/weapons): add bottom dollar bounties dlc weapons

- [core]/es_extended/locales/en.lua
- [core]/es_extended/shared/config/weapons.lua
Added missing San Andreas Mercenaries dlc weapon
- WEAPON_TECPISTOL
> feat(es_extended/shared/config/weapons): add San Andreas Mercenaries dlc weapons

- [core]/es_extended/shared/main.lua
removes event deprication message
> tweak(es_extended/shared/main): remove deprication message

- [core]/es_extended/server/classes/overrides/oxinventory.lua
- [core]/es_extended/server/classes/player.lua
Reverts esx-framework/esx_core#1617
> Revert "feat(es_extended/server/modules/commands.lua): Add Validation Number"

- [core]/esx_menu_default/fxmanifest.lua
- [core]/esx_menu_default/html/css/app.css
- [core]/esx_menu_default/html/js/app.js
- [core]/esx_menu_default/html/ui.html
---
---
---
---
- []  My commit messages and PR title follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard.
- []  My changes have been tested locally and function as expected.
- []  My PR does not introduce any breaking changes.
- []  I have provided a clear explanation of what my PR does, including the reasoning behind the changes and any relevant context.
> Esx menu default

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This PR removes my name from the default assignees
---
So that i dont get notified about issues lol
---
It removes me from the default assignees which will stop me from being assigned to new issues.
---
---
> chore(.github/ISSUE_TEMPLATE): 📥 remove me from default assignees

- [core]/es_extended/client/modules/adjustments.lua
- [core]/es_extended/shared/config/adjustments.lua
> feat(es_extended): Add configurable density multipliers for peds and vehicles

- [core]/esx_multicharacter/readme.md
It replaces the old image from imgur (outdated ui) with a new one hosted on fivemanage.
> refactor(esx_mutlicharacter) Replaced old image of esx_multicharacter.
