esx-framework/esx_core

- [esx_addons]/esx_jobs/client/main.lua
- [esx_addons]/esx_jobs/server/main.lua
- [esx_addons]/esx_policejob/client/main.lua
- [esx_addons]/esx_policejob/config.lua
Fixed a bug in esx jobs where if the caution was set to 0 it wouldn't work. Fixed another bug in esx jobs where the health for the vehicle wasn't being defined. Added a config to policejob for optionalneeds (only used when you want to see how drunk people are)
> Fixed bug and added config

- [esx]/es_extended/client/functions.lua
- [esx_addons]/esx_society/server/main.lua
In my initial commit for this I had mistakenly failed to reset the onlinePlayers table after the first callback.
In the changes I submitted for the compiled repo, I failed to stop multiple loops from running at once or in quick succession. 😞 
- Only one loop will run while the rest wait for it to finish (which is basically instant, anyway)
- Trigger the initial callback independently of the rest
- Wait 1 second before clearing the table
Kept the old functions but shouldn't be getting used, added GetGamePool
> fix & improvement(society & esx): Correct getOnlinePlayers behaviour; update the old enumerate functions

- [esx]/es_extended/locales/en.lua
remove duplicate Locales['en'] key
> fix weapon_combatmg_mk2 Locales['en']

- [esx]/es_extended/client/common.lua
- [esx]/es_extended/client/main.lua
- [esx]/es_extended/server/classes/player.lua
- [esx]/es_extended/server/commands.lua
- [esx]/es_extended/server/common.lua
- [esx]/es_extended/server/functions.lua
- [esx]/es_extended/server/main.lua
- [esx_addons]/esx_addoninventory/server/main.lua
- [esx_addons]/esx_ambulancejob/config.lua
- [esx_addons]/esx_ambulancejob/server/main.lua
- [esx_addons]/esx_mechanicjob/client/main.lua
- [esx_addons]/esx_mechanicjob/config.lua
- [esx_addons]/esx_policejob/client/main.lua
- [esx_addons]/esx_policejob/config.lua
- [esx_addons]/esx_property/client/main.lua
- [esx_addons]/esx_property/config.lua
- [esx_addons]/esx_property/server/main.lua
- [esx_addons]/esx_taxijob/client/main.lua
- [esx_addons]/esx_taxijob/config.lua
- [esx_addons]/esx_vehicleshop/client/main.lua
- [esx_addons]/esx_vehicleshop/config.lua
- [esx_addons]/esx_weaponshop/config.lua
Fairly low effort to get the the basics working.
- Register addon inventories as stashes
- Open inventory with job stashes and search player
- Disable a bunch of standard code or call inventory exports instead
Checks if the resource exists and sets `Config.OxInventory` inside ESX. Other resources just need a simple
```lua
Config.OxInventory = ESX.GetConfig().OxInventory
```
I don't really want to do any more than this.
> feat: setup basic support for ox inventory

- [esx_addons]/esx_ambulancejob/server/main.lua
Otherwise the client event won't trigger and respawn the player
> fix(ambulancejob): return callback when removing items

- [esx_addons]/esx_drugs/client/weed.lua
cannot pickup weed plant 
because distance from player coords and weedplant object 
the distance is too small 
should be 1.5 not 1.0
> Fix Bug: Cannot pickup weed plant

- [esx_addons]/esx_garage/client/main.lua
https://cdn.discordapp.com/attachments/817059034699399259/944153115534458880/unknown.png
because registerType instance garage it call a function when "script instance" running setup script.
we should wait script "instance" loaded or setup successfully 
and we will be able to execute the "register instance type" function
> Fix Error: esx_garage when player enter to zone

- [esx]/es_extended/server/classes/player.lua
Having to update accounts with physical items to sync in multiple places just makes for a bad time.
> fix(esx/player): improve accounts sync with ox inventory

- [SQL]/legacy.sql
If the players are saved with a rockstar license, forty is very little, so when giving invoices, there is an error in the notifications.
> Increase sender length to 60

- [esx_addons]/esx_lscustom/client/main.lua
Loop now in affect and doesn't crash, because of missing `Wait(0)`
> refactor(esx_lscustom/client/main.lua): fixed loop

- [esx_addons]/esx_jobs/fxmanifest.lua
Fix for this: 
After doing that ^, thought about other errors and here we go, ~~we can't start job lua's before we load `client` and `server` lua's~~. Actually `main.lua:28` uses locales, so we can load them from shared_scripts apparently.
> [script:esx_jobs] SCRIPT ERROR: @esx_jobs/server/main.lua:28: attempt to index a nil value
fix #210
> refactor(esx_jobs): Correct start order for functioning

- [esx_addons]/esx_ambulancejob/locales/br.lua
- [esx_addons]/esx_ambulancejob/locales/cs.lua
- [esx_addons]/esx_ambulancejob/locales/de.lua
- [esx_addons]/esx_ambulancejob/locales/en.lua
- [esx_addons]/esx_ambulancejob/locales/es.lua
- [esx_addons]/esx_ambulancejob/locales/fi.lua
- [esx_addons]/esx_ambulancejob/locales/fr.lua
- [esx_addons]/esx_ambulancejob/locales/hu.lua
- [esx_addons]/esx_ambulancejob/locales/nl.lua
- [esx_addons]/esx_ambulancejob/locales/pl.lua
- [esx_addons]/esx_ambulancejob/locales/si.lua
- [esx_addons]/esx_ambulancejob/locales/sv.lua
- [esx_addons]/esx_ambulancejob/locales/tr.lua
Removed some extra spacings, added amount of money to respawn_bleedout_fine_msg and corrected respawn key in distress_send.
In most of the variables invalid_amount the sentence is cut, someone who knows the respective language of each file would have to solve it.
> fix(locales) esx_ambulancejob translation file

- [esx]/es_extended/server/classes/overrides/oxinventory.lua
This iteration should only occur when passing a truthy argument,
otherwise return the full table as-is.
Function was broken in https://github.com/esx-framework/esx-legacy/commit/ef6b66ab3ea9dcdbfc7f88d607cb75750f43b81f.
> fix(esx/server): xPlayer.getInventory return using ox_inventory

- [esx]/es_extended/server/commands.lua
- [esx]/es_extended/server/functions.lua
It's cleaner than forcing stuff to an argument type that just skips validation altogether.
And will be useful in the future for new commands utilising the validate variable.
> minor change: add support for skipping validation of single command arguments

- [esx]/es_extended/client/functions.lua
Natives "GetVehicleLivery" and "SetVehicleLivery" doesn't work anymore.
Replaced broken natives in "ESX.Game.GetVehicleProperties" and "ESX.Game.SetVehicleProperties" with "GetVehicleMod" and "SetVehicleMod" with modType 48
https://forum.cfx.re/t/setvehiclelivery-not-working-even-when-setting-setvehiclemodkit-to-0
> fix(es_extended/client/functions.lua) Livery Mod Get/Set-VehicleProperties

- [esx]/es_extended/server/functions.lua
If the script that registered an item callback has stopped and ESX.UseItem is used, an error will occur (but seemingly with no message??).
```
[  script:es_extended] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:479: attempt to concatenate a nil value (local 'err')
[  script:es_extended] > cb (@ox_inventory/server.lua:242)
[  script:es_extended] > handler (@ox_lib/callback/server.lua:59)
```
```
[ citizen-server-impl] Stopping resource esx_mechanicjob
[  script:es_extended] [WARNING] An error occured when using item "carokit"! This was not caused by ESX.
```
> fix(esx/server): use protected calls for Item Callbacks

- [esx_addons]/esx_ambulancejob/client/job.lua
The first parameter in the event esx:setJob was used in the wrong way, job is returning a table however we want job.name to get the name of the job, if we check <a href="https://github.com/esx-framework/esx-legacy/blob/main/esx_example/client/main.lua">esx_example</a> it's used in the same way
> refactor: esx_ambulance/client/job.lua esx:setJob fixed

- [SQL]/legacy.sql
This small change will allow anyone using legacy to quickly see via sql when a user account was created and when the user was last active.
> Feat(Legacy.sql): Timestamps for User Creation

- [esx]/es_extended/server/classes/player.lua
Functions were receiving table instead of a string.
> Buying weapon attachments bug fix

- [esx]/es_extended/server/onesync.lua
Fixes the Invalid Lua type error.
```
SCRIPT ERROR: Invalid Lua type in __data
> fn (@es_extended/server/onesync.lua:91)
```
> fix(es_extended): onesync.lua coords variables

- [esx]/es_extended/server/classes/player.lua
Recently came across a guy in my community who tried to use this function, but he got this error. 
Obviously, this is not that helpful and I would presume that it is not the first time someone passed an unknown item into this function and got this error.
> Added a check to display a more precise error message
> refactor(es_extended/server/classes/player.lua): xPlayer.canCarryItem - Error handling - Item not found

- [esx_addons]/esx_lscustom/client/main.lua
- [esx_addons]/esx_lscustom/server/main.lua
save props and net id in object for source id and vehicle plate .
update props when buy any mod ( when save in database ) .
remove vehicle object from source object when parent menu closed .
mod restore when server players count more than 0 .
vehicle entity remove from server when players count are 0 .
Thanks to @iSentrie  for help in testing resource
Issue :   #289
> refactor(esx_lscustom) : fix free tuning glitch

- [esx_addons]/esx_lscustom/client/main.lua
- [esx_addons]/esx_lscustom/config.lua
Hi,
this fixes the default value for wheels.
Currently, if you change to custom wheel type you can never go back to the car default wheels.
Regards
> fix(esx_lscustom): default wheels

- [esx]/es_extended/client/functions.lua
The first return parameter of GetVehicleXenonLightsCustomColor is a boolean indicating if the vehicle has custom color.
> fix(es_extended): GetVehicleProperties custom xenon color

- [esx]/es_extended/client/functions.lua
Hi,
Sometimes to reset a vehicle mod, esx_lscustom sends the value "false" in vehicle props.
But "nil" and "false" are ignored by esx.
This change makes it so that only "nil" is ignored but false is sent so we can reset any value.
Regards
> fix(es_extended): value reset if receiving "false" 

- [esx]/es_extended/client/main.lua
- [esx]/es_extended/server/classes/player.lua
- [esx]/es_extended/server/main.lua
- [esx]/es_extended/server/onesync.lua
this is a threadless design that allows both xPlayer.coords and xPlayer.getCoords to correctly function, aswell as removing the need for the client to trigger a server event this is once again, a change that **requires** Onesync **infinity**
> refactor(es_extended): Server sided Coord Saving + fix spawning of invalid vehicles

- [esx]/esx_context/index.html
- [esx]/esx_context/main.lua
- [esx]/esx_multicharacter/client/main.lua
Added canClose to context menu so that players can't close the menu by pressing ESC instead must be force closed in the code.
> feat: add canClose to context menu

- [esx]/es_extended/client/main.lua
On Itme Remove/Add the Default Inventory will now only show if enabled in the es_extended Config!
> Only show Default Inventory if Config enabled.

- [esx_addons]/esx_lscustom/config.lua
Fix for vehicles that has 5 engine upgrades, example `shinobi` Prevents errors.
Also adjusted prices, swapped places brake prices and a little adjusted engine prices, which looks too
> fix(esx_lscustom): Added 5th engine level

- [esx]/esx_menu_default/client/main.lua
Reduce usage to 0.0
faster key press then isControlePress
Close all menu's when namespace or resource restarted ( prevent stocked menu )
> refactor(esx_menu_default/client/main.lua): Change isControlePress to ESX.RegisterInput

- [esx_addons]/esx_service/server/main.lua
- esx:playerDropped event was not working properly, source was not working, changed it to playerId
- Added GlobalState[name] to make it easier to track onduty counters
Tested on my local server using 1.9
> refactor(esx_service/server/main.lua): Added some new globalstate stuff and fixed stuff

- [core]/es_extended/config.lua
- [core]/es_extended/server/commands.lua
- [core]/es_extended/server/onesync.lua
Some changes on ESX.OneSync.SpawnVehicle
- If you now sitting in vehicle and use command your vehicle will be deleted
- Default vehicle is now adder
- Vehicles are displayed immediately without delay. And it doesn't bug and throw people away.
- esx:requestModel was deleted because this function does not need it... Mycroft Mycroft.
> ESX.OneSync.SpawnVehicle and Command rewrite

- [core]/es_extended/common/modules/table.lua
Example usage:
`ESX.Table.TableContains(category, {'plane', 'helicopter'})` 
`ESX.Table.TableContains(category, 'boat')`
Just a small function that might be neat to have
> feat(es_extended/common/modules): TableContains

- [core]/es_extended/locales/de.lua
The translation for the standard clip and the extended clip was changed because they meant default grip and extended grip in german.
> Update de.lua - 変態#9999

- [core]/esx_multicharacter/server/main.lua
Use dummy identifier in the multicharacter resource when determining player identifier. This syncs the functionality to what already is happening in `es_extended/server/functions.lua` `ESX.GetIdentifier` method.
Without this, multicharacter resource does not detect existing characters when running under fxdk and will always prompt the user to create a new one, which will fail on the INSERT query due to duplicate primary keys.
> feat(esx_multicharacter): Use dummy identifier for multicharacter when in fxdk mode

- [core]/es_extended/server/classes/overrides/oxinventory.lua
Change was excluded from https://github.com/esx-framework/esx_core/commit/2851032034f93eb48863b909f2bfdb9c7b3fa76f
> fix(esx/ox_inventory): trigger esx:setAccountMoney when syncing inventory

- [core]/es_extended/server/functions.lua
added so you can merge the args for reports command and other functions when you are sending a message with spaces. Needs to be the last args and validate set to false. / Fores
> feat(es_extended/server/functions.lua): "merge" args type in ESX.RegisterCommand

- [core]/es_extended/config.lua
- [core]/es_extended/server/commands.lua
1. Added config variable to config.lua to enable/disable admin logging.
2. Added ESX.DiscordLogFields function to a number of sensitive admin commands (such as /setaccountmoney and /giveweapon).
> feat(es_extended): Added logging to Discord for sensitive group.admin commands

- [core]/es_extended/server/classes/player.lua
This pull request adds the xPlayer.showAdvancedNotification function to the xPlayer object just like xPlayer.showNotification and xPlayer.showHelpNotification.
> feat(es_extended/server/classes/player.lua): Add showAdvancedNotification function

- [core]/es_extended/server/classes/player.lua
This fixes that the xPlayer.showNotification function has the same parameters as that of the esx:showNotification event on the client side allowing you to use the parameters `type` and `length` from the xPlayer object.
> fix(es_extended/server/classes/player.lua): Fix showNotification function parameters to correspond with esx:showNotification event

- [core]/es_extended/client/main.lua
- [core]/es_extended/server/classes/player.lua
This pr changes the function for xPlayer.removeWeapon by using rpc natives to remove the weapon serverside instead of using a client event.
> Remove weapon using rpc

- [core]/es_extended/server/classes/player.lua
**Support for Clearing Specific Value:**
You can now use the "clearMeta" function to remove a specific value associated with an index. By providing the "index" and the "subValue" (as a string), the function will remove that specific value from the metadata table.
**Support for Clearing Multiple Values:**
The function has been expanded to allow the removal of multiple values simultaneously. By passing a table of "subValues" to the function, you can specify several values to clear from the metadata table associated with a particular index.
**Handling Entire Index Value:**
If no "subValues" are provided, the function will clear the entire value associated with the given "index." This allows you to wipe out all the data related to that particular index.
**Clear the entire value associated …
> Enhanced xPlayer Metadata Management Function

- [core]/es_extended/config.lua
- [core]/es_extended/server/main.lua
someone asked for it so i did it 👯‍♂️
> Added start items feature

- [core]/es_extended/server/functions.lua
/dv command radius args now optional
> :ambulance: fix register commands handle optional args

- [core]/cron/server/main.lua
Description:
This commit brings substantial enhancements to the time handling functionality in the 'esx_core/[core]/cron/server/main.lua' script for the FiveM server:
- Utilized Unix Timestamps: Replaced the existing `GetTime()` function with `GetUnixTimestamp()`, ensuring precise time representation by using the Unix timestamp format (seconds since January 1, 1970). This change mitigates potential issues related to Daylight Saving Time (DST) transitions.
- Refined Task Execution Logic: The `OnTime` function has been refactored to operate based on Unix timestamps, ensuring accurate execution of scheduled tasks without any inconsistencies due to local time conversions.
By introducing these improvements, the cron-like system now operates with enhanced accuracy, bolstering the stability and …
> 🚀 Enhanced ESX Core Cron Task Handling

- [core]/es_extended/server/onesync.lua
By using the function you see the following:
source = GetPlayerPed(source)
-- So source is now the playerPed
source = GetEntityCoords(GetPlayerPed(source))
-- The source is getting new defined by calling the entity coords from the playerPed and then the playerPed once again.
> Fixing getNearbyPlayers function source definition

- .github/workflows/main.yml
- [core]/es_extended/server/commands.lua
- [core]/es_extended/server/functions.lua
This pull request introduces a new argument type, 'coordinate', to the existing `setcoords` command. The 'coordinate' argument type allows more flexible input formats for specifying coordinates, accommodating user feedback and enhancing usability. The changes are made in response to a feature request discussed in [GitHub Issue #1143](https://github.com/esx-framework/esx_core/issues/1143).
In this pull request, a new argument type 'coordinate' has been added to the `setcoords` command. The code snippet for handling this argument type has been enhanced as follows:
```lua
elseif v.type == 'coordinate' then
local coord = tonumber(args[k]:match("(-?%d+%.?%d*)"))
if not coord then
error = TranslateCap('commanderror_argumentmismatch_number', k)
else
newArgs[v.name] = coord
end
end
```
This …
> Feature Request 1143: Added 'coordinate' arg type for ESX.RegisterCommand()

- .github/workflows/main.yml
- [core]/es_extended/client/functions.lua
I have encountered several frustrating instances when accidentally restarting a script that still had an open ESX UI. This situation prevents the UI from closing properly and leads to a cascade of errors, ultimately forcing a game restart. To address this issue, I propose the following code changes.
The code introduces an event handler for the onResourceStop event, enabling us to loop through all open ESX UIs and identify any opened menus within the same namespace as the resource name. Following the best practice, the namespace should ideally align with the resource name.
I believe implementing these changes will provide a smoother user experience. I look forward to your feedback and merging these improvements into the main branch.
> fix(ESX.UI): Close Opened Menus on Resource Stop

- [core]/es_extended/client/functions.lua
- [core]/es_extended/client/main.lua
- [core]/es_extended/server/classes/player.lua
- [core]/es_extended/server/functions.lua
- [core]/es_extended/server/main.lua
This pull request introduces a critical security update for the "esx:onPickup" event to mitigate potential abuses. The update incorporates a distance check mechanism, preventing players from exploiting the event to collect pickups from excessive distances. This measure ensures fair gameplay and maintains the integrity of the event.
- Store serverside pickup coords as a vector, eliminating the need for client-side conversion, and allowing for arithmetic operations on them. 
- Implemented a distance check within the existing 'esx:onPickup' event handling code.
- If a player attempts to interact with a pickup beyond a specified distance (5.0 units), a warning is triggered, and the interaction is blocked.
The modified code snippet is as follows:
```lua
RegisterNetEvent('esx:onPickup') …
```
> Security Enhancement: Distance Check for 'esx:onPickup' Event

- [core]/es_extended/client/functions.lua
The gas tank trailer replaces all vehicles with the "Utility" class (number 11). 
I fixed the spawn by removing the number 11 from the list to spawn these vehicles as "automobile" and not as "trailer".
> Fixed the spawn of vehicle with "Utility" class

- [core]/es_extended/server/classes/player.lua
This pull request addresses an issue related to integer underflow in the code for updating player account balances. The issue could potentially allow the account balance to go below the minimum representable value for integers and underflow to the maximum representable value. To mitigate this problem, the following changes have been made:
- Added an additional check to ensure that the subtraction of `money` from the account balance won't result in a balance higher than the current value.
```lua
if self.accounts[account.index].money - money > self.accounts[account.index].money then
print(('[^1ERROR^7] Tried to underflow account ^5%s^0 for Player ^5%s^0!'):format(accountName, self.playerId))
return
end
````
An attacker could potentially exploit this vulnerability in the following manner:
- …
> Prevent Integer Underflow in Account Balance Update

- [core]/es_extended/client/modules/actions.lua
Player health regenerating even when it's disabled. It needs to be re-setted on ped change.
> fix(es_extended/client/modules/actions): player health regeneration

- [core]/es_extended/server/functions.lua
skin_male and skin_female fields in job_grades table does not have a default value and there for server console spits error when creating job in runtime. This is now fixed.
> ESX.CreateJob - Fixed error for skin no default value

- [core]/es_extended/server/functions.lua
Added a function 'ESX.DeleteJob' to be used in runtime to delete jobs.
> Added ESX.DeleteJob for Runtime

- [core]/esx_multicharacter/config.lua
there is used SpawnCoords.w in script many times but in config is value defined as heading so it ignores heading and it's set to nil
> fix(multicharacter/config): predefined spawn with incorrent defined heading

- [core]/es_extended/server/classes/overrides/oxinventory.lua
Client side maxWeight in ox_inventory is not synced when setting it using .Set
> fix: ox_inventory setMaxWeight client-side sync

- [core]/es_extended/server/functions.lua
This pull request introduces a new function `ESX.TriggerClientEvent` to the ESX framework. In the FiveM environment, the native `TriggerClientEvent` is limited to triggering events for a single player ID at a time. This limitation incurs significant overhead when sending events to multiple clients, as the data must be re-serialized for each client. The new function addresses this issue by serializing the data once using msgpack and efficiently triggering events for multiple clients using the internal native `TriggerClientEventInternal`.
- Added `ESX.TriggerClientEvent` function to the ESX framework.
- Utilized msgpack for serializing additional arguments once, reducing overhead.
- Implemented logic to trigger events for multiple clients using the internal native …
> feat(es_extended/server/functions): add ESX.TriggerClientEvent

- [core]/es_extended/common/functions.lua
Add a utility function that allow to check value types
as I say in source code
Need feedback on this one, should we assert or return false and error message?
I prefer assert, but I'm open to suggestions
Thank you.
Here an examples
Example: 1
```lua
local value = 1
ESX.TypeCheck(value, "number") -- true
```
Example: 2
```lua
local value = "hello"
ESX.TypeCheck(value, "number", "string") -- true
```
Example: 3
```lua
local value = "hello"
ESX.TypeCheck(value, "number") -- false, "bad value (number expected, got string)"
```
Example: 4
```lua
local value = "hello"
ESX.TypeCheck(value, "boolean", "number", "table") -- false, "bad value (boolean or number or table expected, got string)"
```
Example: 5
```lua
local value = nil
ESX.TypeCheck(value, "boolean", "number", "table") -- false, "bad …
```
> feat: add TypeCheck to check value types

- [core]/esx_multicharacter/server/main.lua
Now the script can delete rows where the table name contains a special character like a -
> fixed sql query main.lua

- [core]/esx_menu_default/html/js/app.js
jQuery can't handle getting elements with `$("#...")` if the name contains a colon and takes it as another query. By getting the element via `document.getElementById` and wrapping it with `$(...)`, the functionality remains the same, but menu names can have a colon and other characters in them and the menu will open and not throw an error saying it didn't find the element.
Previously it was throwing `Uncaught TypeError: Cannot read properties of undefined (reading 'scrollIntoView') (@esx_menu_default/html/js/app.js:67)` because it couldn't find the element.
> fix(esx_menu_default): jquery handling element id

- [core]/es_extended/client/common.lua
- [core]/es_extended/common/object.lua
- [core]/es_extended/fxmanifest.lua
- [core]/es_extended/server/common.lua
Reverts esx-framework/esx_core#1346
> Revert "refactor(es_extended): put identical object related code into one file"

- [core]/es_extended/server/main.lua
This error occurs when you use command that doesn't exist and your data is not loaded (command used in F8 while I was in multicharacter menu)
> fix(server): attempt to index a nil value (local 'xPlayer')

- [core]/es_extended/client/functions.lua
- [core]/es_extended/client/modules/streaming.lua
Big refactor to client functions with no breaking changes (allegedly).
Except for ESX.Game.SpawnObject that returns the object synchronous if no callback provided.
(Just a new behaviour, keeps working as used to)
Added new functions:
· ESX.DrawMissionText
· ESX.Game.GetShapeTestResultSync **
· ESX.Game.RaycastScreen **
** Last two are used to improve the performance of ESX.Game.GetVehicleInDirection
It already uses a Synchronous Shape Test Result less performant than solution provided.
In streaming functions, ff no callback provided, functions will return the first argument synchronously.
if not, first argument will be passed to the callback.
> refactor(es_extended/client/functions.lua) and (es_extended/client/modules/streaming.lua)

- [core]/es_extended/server/modules/createJob.lua
This patch improves the job creation process by using a complete SQL transaction to ensure that insertions into both the `jobs` and `job_grades` tables are atomic. The use of `INSERT IGNORE INTO jobs` has been corrected to avoid inconsistencies in retrieving the job ID, and all insertion steps are now part of a transaction to ensure that the job and its grades are created reliably.
```lua
lib.callback.register('advanced_management:staff:creator', function(source, type, data)
if type == 'job' then
local name = data.name
local label = data.label
local grades = data.grades
local success = ESX.CreateJob(name, label, grades)
-- Wait(500)
if not success then
return false
end
local jobs = ESX.GetJobs()
if jobs[name] then
lib.notify(source, {title = 'Success', description = 'The job was …
```
> Dev - Fix job creation with full transaction for `jobs` and `job_grades` tables

- [core]/esx_notify/nui/js/script.js
If invalid notify type is provided, it throws an error to console
> fix(notify): no valid icon

- [core]/es_extended/client/main.lua
- [core]/es_extended/server/classes/player.lua
- [core]/esx_identity/server/main.lua
Currently, everything flowing through xPlayer.set is being put into a statebag, aswell as all metadata , resulting in crashes.
This change is a high priority.
> !Refactor(core): Statebag removal and changes

- [core]/es_extended/client/functions.lua
Should be self-explanatory, it would make things a lot easier if you could close directly with the cancel function instead of just using the close function.
> Add an option to use the cancel function instead of the close function when closing a menu or all menus.

- [core]/es_extended/client/functions.lua
In the last update, **RegisterInput** tries to execute the command on key release due some checks removal in #1303. The check was restored and tested.
**HashString** breaks when the joaat returns a hash bigger than 2^31. It was fix using a [shift mask](https://stackoverflow.com/a/20294714).
> fix(es_extended/client/functions.lua) RegisterInput and HashString bug

- [core]/es_extended/config.lua
by default, use the txAdmin locale, unless a `esx:locale` is specified.
This allows people to change languages easier, since everything will be in the same place, and if they want to specify a different language for ESX, then they can do.
This also wont break anything, since it wont affect existing users whom will aready have the `esx:locale` set
> tweak: use txAdmin locale by default 

- [core]/es_extended/server/modules/createJob.lua
self.setJob in es_extended/server/classes/player.lua decodes skin data, which means skin data should be a string and not a table. When creating shops in run time and setting this job, it would throw error.  Modified so it's a string and also added compatibility to parse skin_data directly into the job grade.
> fix(createJob): skin error

- [core]/es_extended/common/modules/math.lua
This PR adds `ESX.Math.GetHeadingFromCoords`, a utility function to get the heading in degrees from one coordinate to another.
---
- Added `ESX.Math.GetHeadingFromCoords` for quick heading calculations between two vector coordinates.
- Uses trigonometry to calculate direction and normalizes the output between 0° and 360°.
---
This utility is handy for any direction-based checks in ESX, making it easier for devs to get accurate headings without reinventing the wheel.
---
Tested locally with various coordinate pairs; consistently returns correct headings. Handles all directional variations as expected.
---
An alternative method could be using the `GetHeadingFromVector_2d` native, as discussed [here](https://forum.cfx.re/t/help-how-to-set-ped-looking-at-position/19294/6). However, using …
> feat(common/modules/math): Add ESX.Math.GetHeadingFromCoords

- [core]/es_extended/config.lua
- [core]/es_extended/server/classes/player.lua
- [core]/es_extended/server/commands.lua
This pull request enhances the player function, `xPlayer.setJob`, within the ESX framework to accept an optional boolean parameter `onDuty`. If the parameter is not set, we fall back on a config-specified default value. This effectively implements a complete job duty system, eliminating the clutter of unnecessary job variations such as "off_police" in your jobs table.
Additionally, developers can now listen for on/off duty changes using the existing `esx:setJob` event. The updated job object includes a new boolean property, `onDuty`, and for ease of use and compatibility, the `jobDuty` property is stored as metadata for each player.
---
- Enhanced the `xPlayer.setJob` function to handle the new optional `onDuty` parameter.
- Introduced a new `onDuty` property in the job object to …
> feat(server/classes/player): Add job duty

- [core]/cron/server/main.lua
minute in the os.time table should be min instead of minute.
Callback function should return the day as the first argument, as README stated (and as how previous version works).
> Fix minute not working, put back day check

- [core]/es_extended/client/imports/point.lua
- [core]/es_extended/client/modules/points.lua
This PR includes two key updates to the `points` module:
- Safely iterates over the sparse `points` table in `StartPointsLoop` by using `pairs` instead of `#points`, ensuring that `nil` entries are properly skipped during iteration.
- Fixes a typo in the `ESX.CreatePointIntenal` function name, correcting it to `ESX.CreatePointInternal` for consistency with the correct method name.
> fix(client/modules/points): Small improvements.

- [core]/esx_skin/server/main.lua
This PR adds at least a little validation before saving the contents of the 'skin' net event parameter to the database. You could previously save basically anything to the db that could be stringified as json, which isn't optimal.
> Validate player skin before saving to db

- [core]/es_extended/locales/es.lua
- [core]/es_extended/locales/hu.lua
This PR removes unused duty locales from the Spanish and Hungarian locale files.
> refactor(locales): Remove unused duty locales

- [core]/es_extended/client/modules/actions.lua
This PR fixes an issue in the `TrackPed` function where the new ped ID (`PlayerPedId()`) was not being correctly saved to `ESX.PlayerData.ped`. As a result, the loop in the function detected constant changes and triggered unnecessary events.
--- 
- Updated `TrackPed` to properly save the new ped ID.
- Ensured `ESX.SetPlayerData` uses the updated ped reference.
- Passed the new ped to the `esx:playerPedChanged` event.
---
- Verified that the new ped ID is updated in `ESX.PlayerData.ped` as expected.
- Confirmed that the loop no longer runs indefinitely once the ped is updated.
- Checked that the `esx:playerPedChanged` event fires correctly with the new ped data.
---
This fix resolves unnecessary resource usage caused by continuous ped tracking and improves overall performance.
> fix(es_extended/client/modules/actions): correctly update ped reference in TrackPed

- [core]/skinchanger/client/main.lua
- Fixed an issue where head overlays were not being applied properly due to incorrect overlay order.
- The overlay order has been corrected, ensuring that the head overlays are now applied as intended.
[Native Reference](https://docs.fivem.net/natives/?_0x48F44967FA05CC1E)
> fix(skinchanger/client/main): fix HeadOverlay not being applied correctly

- [core]/es_extended/client/functions.lua
As the title says, this fixes a bug that occurs when using the menu- close or close all function with the cancel argument set.
The error was that the Cancel function was called without any further arguments, as it normally is.
> fix(es_extended/client/functions.lua): bug fix with the menu close & closeall function

- [core]/es_extended/client/modules/callback.lua
example usage:
```lua
RegisterCommand("callback", function ()
local value, value2 = ESX.AwaitServerCallback("es_extended:callbackTest")
print(value, value2)
end, false)
```
> feat(es_extended/client/callback): implement ESX.AwaitServerCallback

- [core]/esx_skin/client/modules/menu.lua
This PR resolves a bug mentioned in [#1491](https://github.com/esx-framework/esx_core/issues/1491) where components from a previous skin menu persist when switching between menus (e.g., hair options showing in the clothing shop).
> fix(esx_skin/client/modules/menu): clear old menu items before inserting new ones

- [core]/esx_skin/client/modules/menu.lua
This PR addresses an issue where the initial camera offsets were not set properly when opening a skin menu.
> fix(esx_skin/client/modules/menu): set initial camera offsets properly

- [SQL]/legacy.sql
This PR sets the `model` column as the primary key for the existing `vehicles` table.
---
- **Data Integrity**: The primary key enforces uniqueness, ensuring each vehicle can be distinctly identified.
- **Ease of Editing**: With a primary key in place, we can easily manage and edit rows in tools like phpMyAdmin.
> refactor(SQL/legacy): Add primary key to vehicles table

- [core]/es_extended/client/functions.lua
The native [SetVehicleExtra](https://docs.fivem.net/natives/?_0x7EE3A3C5E4A40CC9) dictates whether a vehicle extra should be **disabled**, while [IsVehicleExtraTurnedOn](https://docs.fivem.net/natives/?_0xD2E6822DBFD6C8BD) returns whether an extra is **enabled**. The latter is saved in the DB as vehicle properties. So we need to negate that value to properly reflect which vehicle extras we should toggle. This also fixes issues with helicopters missing key body parts when being parked out from garages, as the vehicle extras are being removed when they should not.
> fix(es_extended/client/functions): properly call SetVehicleExtra

- [core]/esx_multicharacter/server/modules/multicharacter.lua
Added a missing parameter that wouldnt allow users to have custom charSlots
> fix(esx_multichar/server/modules/multicharacter.lua): Added missing parameter

- [core]/es_extended/shared/functions.lua
- [core]/esx_skin/client/modules/menu.lua
- [core]/skinchanger/config.lua
- In `Menu:InsertElements()`, we now clone the current component before inserting it into the menu. This prevents overwriting the max value, preserving its function reference and ensuring it can still update dynamically on menu changes.
- Added `ESX.IsFunctionReference` to reliably determine if a value can be treated as a callable function.
- Limited updates to `self.elements` only when a texture (not a texture variation) changes.
- Updated only the specific texture variation's max value instead of iterating over and updating the entire menu.
- Added missing texture dependency for texture variation `hair_2`
> fix(esx_skin/client/modules/menu): fix texture variations not updating

- [core]/es_extended/client/main.lua
- [core]/es_extended/shared/config/main.lua
- [core]/esx_multicharacter/client/modules/multicharacter.lua
The current spawn event flow for multicharacter is structured as follows:
1. The player loads into the server, triggering the `playerSpawned` event during multichar setup.
2. On character selection, the following events are triggered in this order:
1. `esx:playerLoaded`
2. `playerSpawned`
3. `esx:onPlayerSpawn`
4. `playerSpawned` *(Redundant and removed by this PR)*
This PR addresses **two key issues**:
1. **Redundant `playerSpawned` Trigger**  
The `playerSpawned` event was redundantly triggered in the `ESX.SpawnPlayer` function callback, even though the function itself already triggers this event. This PR eliminates the unnecessary duplication.
2. **Health & Armor Metadata Race Condition**  
Player metadata, such as health and armor, is now applied within the `esx:onPlayerSpawn` event …
> fix(es_extended/client/main): fix player death race condition

- [core]/es_extended/client/modules/death.lua
This refactor replaces the use of `gameEventTriggered` with a more efficient, thread-based solution for handling player deaths. The previous approach relied on the `CEventNetworkEntityDamage` event, which was triggered too often, specifically for non-lethal events like vehicle crashes, causing unnecessary performance overhead. The new solution checks for player death deterministically in a thread, only triggering the death event when a player is confirmed dead.
Additionally, the typo in the `Natual` function name was corrected to `Natural` for consistency.
--- 
This change was motivated by concerns raised by @Gellipapa about the inefficiency of using `CEventNetworkEntityDamage` for detecting player deaths.
> refactor(es_extended/client/modules/death): replace gameEventTriggered

- [core]/es_extended/client/main.lua
Introduced [`NetworkSetLocalPlayerSyncLookAt`](https://docs.fivem.net/natives/?_0x524FF0AEFF9C3973), enabling synchronization of where players are looking between clients.
---
Discovered while exploring the [Cfx Discord](https://discord.com/channels/192358910387159041/1219992387833561119/1224296191320395786). Special thanks to @glowicosahedron for sharing this information and providing the demonstration video.
[Video Preview](https://github.com/user-attachments/assets/23a6a37b-9ac9-4554-ae07-1de8e562bcea)
> feat(es_extended/client/main): sync where players look at

- [core]/es_extended/locales/en.lua
- [core]/es_extended/server/functions.lua
- [core]/es_extended/server/modules/commands.lua
This PR resolves an issue where teleporting to another player or bringing a player to you as an admin did not ensure that both players were in the same dimension. This behavior is counterintuitive, as admins would expect the player to appear directly in front of them, not in a different dimension. To address this, the commands now automatically set both players to the same dimension during teleportation. Additionally, a `/setdim` admin command has been added to allow manual dimension adjustments if necessary.
- Added the `/setdim <targetSrc> <targetDim>` admin command, allowing admins to manually set a player's dimension.
- Updated the `/goto` and `/bring` admin commands to ensure both players are placed in the same dimension during teleportation.
---
> feat(es_extended/server/modules/commands): add /setdim cmd

- [core]/es_extended/shared/main.lua
This PR brings back the `esx:getSharedObject` event, a key feature that was removed in ESX 1.9 after being deprecated in 1.8.5. The removal of this event caused compatibility issues with many legacy scripts, leading to frustration in the community.
The proposed solution restores the event and includes a **warning message** encouraging developers to migrate to newer methods. This approach keeps backward compatibility for existing resources while gently guiding the community toward best practices.
---
1. **No Good Reason for Removal**  
- The removal of the `esx:getSharedObject` event didn't come with a clear, justified reason. It was widely used across the ESX ecosystem, and removing it created unnecessary issues. The lack of a technical need for this change meant that many developers and …
> feat(es_extended/shared/main): restore backwards compat

- [core]/es_extended/client/modules/actions.lua
This PR improves the `actions` module by adding functionality to track the currently selected weapon of the player's ped. This eliminates the redundancy of multiple third-party scripts performing the same tracking, reducing overhead. Centralizing this in ESX ensures consistency and simplifies development for server owners and script developers.
---
> feat(es_extended/client/modules/actions): track current ped weapon

- [core]/es_extended/client/modules/actions.lua
This PR ensures that the vehicle seat  in the player data is properly updated when a seat change occurs, such as through shuffling or seat-switching scripts. Additionally, the player's current weapon has been added to the player data.
---
> feat(es_extended/client/modules/actions): track vehicle seat & add weapon playerdata

- [core]/es_extended/client/modules/death.lua
This PR resolves an issue with death detection during multicharacter relogging. Previously, relogging could incorrectly trigger the death event, causing the death screen to appear unexpectedly. Additionally, this PR ensures that no concurrent threads are created during relogging, preventing the death event from being triggered multiple times.
---
> fix(es_extended/client/modules/death): fix death event for multichar relog

- [core]/es_extended/client/functions.lua
- [core]/es_extended/server/modules/onesync.lua
This PR enhances the ESX vehicle spawn functions to allow waiting for vehicle creation using promises, instead of requiring a callback function. Additionally, a resource leak in the `ESX.Game.SpawnVehicle` function has been addressed. The function now returns immediately when an invalid vehicle is requested instead of creating stale threads.
```lua
local vehicle = ESX.Game.SpawnVehicle(model, coords, heading)
local vehNetId = ESX.OneSync.SpawnVehicle(model, coords, heading, vehProps)
```
> feat(es_extended): add promise support for vehicle spawn functions

- [core]/es_extended/shared/functions.lua
This PR adds a utility function, ESX.Await, to simplify waiting for a condition without the need for manual loops. It checks a condition repeatedly until it’s met or the timeout is reached.
Example usage:
```lua
local networkId = ESX.AwaitServerCallback('spawnVehicle')
local function awaitExistence()
return NetworkDoesEntityExistWithNetworkId(networkId)
end
-- timeElapsed value in MS
local success, timeElapsed = ESX.Await(awaitExistence, 'Timed out :(', 3000)
-- we can now mess with the vehicle spawned server-side on the client-side
```
> feat(es_extended) Add ESX.Await function

- [core]/es_extended/shared/config/main.lua
This PR brings ox inventory detection back, because it seems users are unable to read a very simple message
> feat(es_extended/shared): add ox inventory detection back

- [core]/es_extended/server/functions.lua
For some strange reason, the original code `local xPlayer = ESX.Players[playerId]` always returned `null`. However, when changed to `local xPlayer = ESX.Players[tonumber(playerId)]`, it correctly returned the data. Not sure if this is an issue just for me.
> fix(es_extended/server/functions): Core.IsPlayerAdmin returning false

- [core]/es_extended/client/modules/actions.lua
- [core]/es_extended/client/modules/death.lua
- [core]/es_extended/imports.lua
- Fixed an issue where relying on `ESX.PlayerLoaded` to be `true` in importing resources did not garuantee that the ped has fully spawned.
- Fixed an issue with ped changes not propogating to importing resources due to execution order.
- Fixed death module relying on a possibly invalid ped which would trigger the death logic.
---
> fix(es_extended/): fix race conditions & ped change not propogating

- [core]/es_extended/client/imports/point.lua
- [core]/es_extended/client/modules/points.lua
**Inside** thread is now handled in the same resource as long more than one point is nearby.
> refactor(es_extended/client/imports/point.lua) and (es_extended/client/modules/points.lua): Performace Improvement

- [core]/es_extended/server/modules/paycheck.lua
- [core]/es_extended/shared/config/main.lua
Added offDuty paycheck multiplier to the paycheck module.
---
> feat(es_extended/server/modules/paycheck): add offDuty pay

- [core]/es_extended/imports.lua
This PR introduces a new module loading system for the ESX framework. The require function is now available for importing resources, allowing them to load modules properly and efficiently, including those that define classes with metatables. This function includes caching to avoid redundant loads and circular dependency checks to prevent infinite loops.
---
```lua
--- resource1/modules/CStudent.lua
local Student = {}
Student.__index = Student
function Student.new(name, age)
local self = setmetatable({}, Student)
self.name = name
self.age = age
return self
end
function Student:getInfo()
return ("Name: %s | Age: %d"):format(self.name, self.age)
end
return Student
```
```lua
--- resource2/server/main.lua
local CStudent = require("@resource1.modules.CStudent")
local student = …
```
> feat(es_extended/imports): add require

- [core]/es_extended/imports.lua
- [core]/es_extended/server/functions.lua
- Removed usage of optional chaining (a 5.4 feature) in the imports.lua. 
- Fixed return value of `ESX.GetItems`. Returned nil because of [this revert](https://github.com/esx-framework/esx_core/pull/1572)
---
> fix(es_extended/imports): remove lua 5.4 dependency for importing resources

- [core]/es_extended/client/modules/scaleform.lua
This utility function streamlines working with scaleform movie methods, allowing for simpler and more readable calls to scaleform functions. With this change, scaleform methods can be invoked in a much cleaner manner, making it easier to work with complex scaleforms that require multiple method calls.
---
Working directly with scaleforms often leads to messy, hard-to-maintain code, especially when dealing with complex scaleforms that require several method calls. This PR introduces a utility function that abstracts the complexity and simplifies interactions with scaleforms, maintaining readability and reducing boilerplate code.
---
- **Utility Function**: The `ESX.Scaleform.Utils.RunMethod` abstracts away the repetitive boilerplate involved in invoking scaleform movie methods. It handles …
> feat(es_extended/client/modules/scaleform): add scaleform util function and refactor existing scaleforms

- [core]/cron/README.md
- [core]/es_extended/README.md
- [core]/es_extended/imports.lua
- [core]/es_extended/server/functions.lua
- [core]/es_extended/shared/main.lua
- [core]/es_extended/shared/modules/table.lua
- [core]/esx_chat_theme/README.md
- [core]/esx_context/README.md
- [core]/esx_identity/README.md
- [core]/esx_loadingscreen/README.md
- [core]/esx_menu_default/README.md
- [core]/esx_multicharacter/readme.md
- [core]/esx_notify/readme.md
- [core]/esx_textui/readme.md
- [core]/skinchanger/README.md
- readme.md
Merge https://github.com/esx-framework/esx_core/pull/1575, https://github.com/esx-framework/esx_core/pull/1576 & https://github.com/esx-framework/esx_core/pull/1580 into main as a hotfix.
> 1.12.3 hotfix

- [core]/es_extended/client/modules/death.lua
This PR aims to address an [issue ](https://github.com/esx-framework/esx_ambulancejob/issues/68) where the death thread would not start on first spawn when using certain third-party multichar systems. This is not directly an issue with ESX, but more the result of those multichar systems triggering esx events in the wrong order.
> fix(es_extended/client/modules/death): fix death thread on first spawn

- [core]/es_extended/client/modules/adjustments.lua
`SetHudComponentPosition` expects floats while we were passing integers.
---
Hud components were not properly being hidden for some people.
---
> fix(es_extended/client/modules/adjustments): `SetHudComponentPosition` expects float

- [core]/es_extended/client/functions.lua
- [core]/es_extended/fxmanifest.lua
- [core]/es_extended/server/classes/vehicle.lua
- [core]/es_extended/server/common.lua
- [core]/es_extended/server/functions.lua
- [core]/es_extended/server/modules/onesync.lua
This PR introduces a robust vehicle class to the ESX framework, offering developers a standardized way to manage owned vehicle entities in FiveM.
---
The primary motivation for this addition is to address the challenges of managing owned vehicles reliably in a multiplayer environment. Specifically, this class enables developers to:
- **Determine if an owned vehicle is spawned or not:** With this class, it's straightforward to check whether a specific vehicle is currently active in the world or has been despawned.
- **Ensure vehicle validity:** By leveraging entity statebags, the system ensures that each tracked vehicle is indeed the one that was created, avoiding issues caused by network ID reassignment (a common occurrence when entities are deleted and new ones are created).
---
1. …
> feat(es_extended/server/classes/vehicle): add vehicle class

- [core]/es_extended/client/modules/scaleform.lua
- This PR updates the scaleform display logic to ensure that the duration of messages is no longer dependent on the frame rate. The new implementation uses ```GetGameTimer()``` to calculate when the scaleform should stop showing.
---
- The previous implementation of the scaleform showing duration relied on frame-dependent timing, which caused inconsistent behavior on different machines or just different FPS. A 5 second scaleform would hide after ~5 seconds on 100FPS but after ~10 seconds on 50FPS. This change ensures that the showing duration is accurate and not dependent of client framerate.
---
- Replaced the frame-dependent loop ```(sec = sec - 0.01)``` with a time-based calculation using ```GetGameTimer()```.
- The loop now checks the elapsed time in milliseconds instead of …
> refactor(es_extended/client/modules/scaleform): Make scaleforms show duration framerate independent

- [core]/es_extended/imports.lua
- [core]/es_extended/server/classes/player.lua
- [core]/es_extended/server/functions.lua
Introducing **static ESX Player methods** to streamline player handling. Instead of dealing with a bloated `xPlayer` object that can impact performance as player counts grow, this implementation provides a lightweight alternative by dynamically calling only the required functionality through exports.
---
The current `xPlayer` object is overly bloated, storing unnecessary data that scales poorly with larger player bases. This approach addresses these performance concerns while maintaining a syntax familiar to ESX developers.
---
The `ESX.Player` object uses a metamethod to return a lightweight table containing only the player's server ID when called. If the requested player is offline, it simply returns `nil`. For any subsequent method calls, the stored server ID is used to trigger the …
> feat(es_extended): add static player methods

- [core]/es_extended/server/functions.lua
Discord expects field values to be strings. Before sending them to the webhook, we convert everything to string.
---
https://github.com/esx-framework/esx_core/issues/1604
---
> fix(es_extended/server/functions): fix admin logs

- [core]/esx_multicharacter/server/modules/database.lua
Fixes the database name extraction for key-value pair connection strings.
---
> fix(esx_multicharacter/server/modules/database): fix conn string parser

- [core]/es_extended/server/functions.lua
- [core]/es_extended/server/modules/createJob.lua
Missing attributes when indexing unemployed job into ESX.Jobs. Database contains name column for jobs table  and for job_grades it also contain a grade name column.
Also fixed loop method for grades when inserting into queries.
Adds the missing attributes when assigning unemployed to ESX.Jobs if no jobs are found. 
Also fixed loop method for grades when inserting into queries.
---
Because it makes sense
---
N/A
---
3rd party script that compares grades[<grade>].name wouldn't work if this attribute is missing.
Fixes issues where creators parse job grades indexed with strings.
---
> fix(es_extended/server/functions): missing attributes for unemployed

- [core]/es_extended/server/modules/createJob.lua
Added a TriggerEvent when a job is created successfully, allowing developers to use an event listener and update ESX.Jobs, instead of importing the whole ESX object.
Adds a TriggerEvent "esx:jobCreated" with job name (string) and job data (table), to allow allow developers to update/sync ESX.Jobs, using an event listener, without importing the ESX object. 
---
Allowing developers to easily update ESX.Jobs in their script with an event listener, instead of important the whole ESX object to sync the newly created job(s).
---
The event has job name and job data as parameters, so instead of replacing the whole ESX.Jobs, you only add the relevant updates.
---
```lua
RegisterNetEvent("esx:jobCreated", function(jobName, jobData)
if not jobName or type(jobName) ~= 'string' then
return 
end
if not …
```
> feat(modules/createJob): triggerevent for created jobs

- [core]/es_extended/server/classes/overrides/oxinventory.lua
- [core]/es_extended/server/classes/player.lua
- [core]/es_extended/server/modules/commands.lua
This prevents the use of values exceeding the IEEE 754 double-precision floating-point limit.
Entering a value higher than this limit would cause ox to stop functioning and produce the following error: `SEND_NUI_MESSAGE: invalid JSON passed in frame (rapidjson error code 3)`.
Additionally, if you attempt to remove money exceeding this limit, ox would no longer be functioning and you would no longer be able to give any more money. This would require manually resetting your money and removing cash-based items from the database to restore normal functionality.
---
This change prevents admins from unintentionally or maliciously causing issues for players.
---
Improving server-side protections is crucial, as you can never fully anticipate the intentions of people you don’t know well.
More …
> feat(es_extended/server/modules/commands.lua): Add Validation Number

- [core]/es_extended/server/main.lua
GlobalState Jobcount didn't decrease on logout and increased on char select, this way players could infinitely increase the value by relogging multiple times
Fixed this bug for my Server and decided to create a PR
globalstate decreases on logout and increases again on login
no example
> fix(es_extended/server/main): GlobalState jobcount infinitely increasing

- [core]/es_extended/client/modules/callback.lua
- [core]/es_extended/server/modules/callback.lua
- [core]/es_extended/server/modules/paycheck.lua
Adds the `ESX.AwaitClientCallback` function.
#1628 
---
To match `ESX.AwaitServerCallback` and just personal preference.
---
Added the same logic that is used on the client-side to await the server callbacks.
---
```lua
local data = ESX.AwaitClientCallback(source, 'test:client:receiveData', false)
print(json.encode(data))
```
Which can be seen equivalent to
```lua
ESX.TriggerClientCallback(source, 'test:client:receiveData', function(data)
print(json.encode(data))
end)
```
---
> feat(callback): add `AwaitClientCallback` function

- [core]/es_extended/shared/config/main.lua
- [core]/es_extended/shared/functions.lua
- [core]/esx_identity/server/main.lua
This PR refactors the name validation logic by removing the redundant numeric check and simplifying the character validation to handle various character sets like Latin, Greek, Cyrillic, Hebrew, Arabic, and CJK. This change improves the validation process and ensures that only valid characters are accepted, making it more flexible for different language users within the community.
---
The previous validation logic had a redundant numeric check, which was unnecessary because it was already covered by the new character validation logic. This update simplifies the code, improving code readability and making the validation process more flexible. It better supports a wider range of languages and scripts, which is an important step toward making the framework more inclusive for a global …
> Refactor name validation: remove numeric check and simplify character validation

- [core]/esx_identity/config.lua
- [core]/esx_identity/server/main.lua
This PR refactors the age validation logic. It replaces the previous `LowestYear` and `HighestYear` with `MinAge` and `MaxAge`, making the age validation more dynamic and easier to configure. The logic now calculates the minimum and maximum valid birth years based on the current year and the configured `MinAge` and `MaxAge`.
---
This PR was inspired by [#1626 Pull Request](https://github.com/esx-framework/esx_core/pull/1626), where a recent change only adjusted the `MinYear` configuration value. Rather than continuing with static year values, I aimed to provide a more flexible solution by introducing age-based configuration. This allows users to specify the age range directly, making it clearer and easier to manage, especially when maintaining the age validation across multiple versions. …
> Identity age validation

- [core]/es_extended/client/functions.lua
This PR enhances vehicle color compatibility by allowing props.color1 and props.color2 to accept RGB table values (e.g., {255, 255, 255}), in addition to the existing integer-based color indexes. This update ensures compatibility with scripts that utilize RGB values for vehicle customization.
---
Currently, using RGB tables (e.g., via mechanic menus or valet services) causes a runtime error because ESX.Game.SetVehicleProperties expects a number rather than a table. This change ensures a seamless experience for servers and scripts using RGB color customization, preventing native call failures and improving script robustness.
---
Checks if props.color1 or props.color2 is a table.
If so, it uses SetVehicleCustomPrimaryColour or SetVehicleCustomSecondaryColour respectively with the RGB …
> Refactored Set vehicle Properties

- [core]/es_extended/server/functions.lua
added ^0 to ensure proper color reset at the end of the string in console output for command warnings
> fix(es_extended): text color formatting in warning message

- [core]/es_extended/client/modules/events.lua
- [core]/es_extended/server/classes/player.lua
This PR adds another method to xPlayer that lets you use ExecuteCommand() on the xPlayer's client.
---
This lets you run the ExecuteCommand() on a player's client from your server scripts so that you don't have to manually run ExecuteCommand() on the client script.
---
---
```lua
local xPlayer = ESX.GetPlayerFromId(1)
xPlayer.executeCommand("dv 500")
```
---
> feat(es_extended): Add xPlayer.executeCommand Function

- [core]/es_extended/server/main.lua
- [core]/esx_multicharacter/server/modules/functions.lua
- [core]/esx_multicharacter/server/modules/multicharacter.lua
Clean up stale player entries even for players who crashed during multichar select.
---
We already introduced a cleanup mechanism for players who already chose a character, but no such mechancism existed for players who crashed during char select.
---
Save source to ESX.Players table so we can later test if that source is still an active player. Otherwise we can initiate cleanup of the stale player obj.
---
> fix(esx_multicharacter): cleanup stale player obj

- [core]/es_extended/server/functions.lua
- [core]/es_extended/server/modules/onesync.lua
This PR refactors `ESX.OneSync.SpawnVehicle` to decouple vehicle spawning from the presence or proximity of any specific player, and introduces a new optional `routingBucket` parameter to `ESX.OneSync.GetClosestPlayer`.
Previously, we attempted to get the vehicle type from the closest player and then waited for that player to become the network owner (regardless of what dimension they are in). This caused issues when spawning vehicles in other dimensions, specifically when the player was not in dimension 0—blocking vehicle creation indefinitely. Since we spawn vehicles in dimension 0, getting a closest player that is not in that dimension will make it impossible for them to become the net owner of that vehicle and so the spawning will fail.
Now, the logic is much more robust:
- If a …
> fix(es_extended/server/modules/onesync): decouple player proximity from veh spawning

- [core]/es_extended/client/functions.lua
- [core]/es_extended/client/modules/events.lua
Remove the usage of ESX.SecureNetEvent where it doesn't make sense.
---
People have been comlaining that they cannot use esx:showNotification events client-side, among other things.
---
> fix(es_extended): remove usage of SecureNetEvent where it's not needed

- [core]/es_extended/client/functions.lua
- [core]/es_extended/client/modules/events.lua
- [core]/es_extended/locales/en.lua
- [core]/es_extended/server/common.lua
- [core]/es_extended/server/functions.lua
- [core]/es_extended/server/modules/commands.lua
Adds support for creating and refreshing items at runtime.
---
Improves development workflows by allowing items to be added or refreshed dynamically.  
While it's not recommended to refresh items in prod, third-party scripts can call `ESX.AddItems` during startup to register required items without relying on a manual `items.sql` import.
---
```lua
ESX.AddItems({
{
name = "water", label = "Water"
},
{
name = "pd_gadget", label = "PD-Gadget", weight = 10, rare = true, canRemove = false
},
{
name = "bread", label = "Bread"
},
})
```
---
> feat(es_extended): refresh/add items during runtime

- [core]/es_extended/server/main.lua
Fixed missing `cb` parameter in `onPlayerDropped` function
---
Resolving issues with the required `cb` callback function when certain third-party scripts use the `esx:playerLogout` event.
---
Add the `cb` parameter to the `onPlayerDropped` function again.
---
```lua
debugPrint('[LOGOUT] Awaiting Player to be unloaded [/]')
TriggerEvent('esx:playerLogout', source, function()
cb()
debugPrint('[LOGOUT] Player unloaded.')
end)
```
---
-   [X] My commit messages and PR title follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard.
-   [X] My changes have been tested locally and function as expected.
-   [X] My PR does not introduce any breaking changes.
-   [X] I have provided a clear explanation of what my PR does, including the reasoning behind the changes …
> Fix `onPlayerDropped` to pass in `cb`

- [core]/es_extended/client/modules/adjustments.lua
Fix the discord activity that was not working. The problem before was that some variable in for example {server_endpoint}, were never replaced so it created invalid URL and in assetText {server_name} was not replaced too.
---
To fix the discord Presence
---
New function Adjustments:ReplacePlaceholders(text) that replace correctly all the placeholder in a text
Adjustments:PresencePlaceholders() use the new ReplacePlaceholders function to create the presence text.
SetDiscordRichPresenceAssetText and buttonUrl use ReplacePlaceholders to replace the placeholders by the actuals values
---
```lua
function Adjustments:ReplacePlaceholders(text)
for placeholder, cb in pairs(placeHolders) do
local success, result = pcall(cb)
if not success then
error(("Failed to execute placeholder: …
```
> Fix Discord Rich Presence integration

- [core]/es_extended/shared/functions.lua
Fixes a bug in `ESX.GetConfig` where falsy config values (e.g., `false`, `nil`) would incorrectly cause the function to return the entire `Config` table instead of the actual value. This ensures accurate value retrieval even for falsy config values.
---
The previous inline logic using `and`/`or` would fall back to returning the full config if `Config[key]` was falsy. This behavior was incorrect and caused issues when a config value was intentionally `false`. This change fixes that logic.
---
Replaced the ternary-style one-liner with a simple `if` statement to explicitly check if the `key` parameter is not `nil`. This avoids misinterpreting falsy values and ensures proper return values.
Updated function:
```lua
---@param key? string Key pair to get specific value of config
---@return …
```
> fix(es_extended/shared/functions): fix ESX.GetConfig bug

- [core]/es_extended/client/modules/events.lua
- [core]/es_extended/imports.lua
- [core]/es_extended/server/classes/player.lua
- [core]/es_extended/shared/functions.lua
This PR ensures the `ESX.PlayerData.inventory` and `ESX.PlayerData.loadout` tables remain synchronized between client and server & importing resources. It listens for secure events (`esx:addInventoryItem`, `esx:removeInventoryItem`, `esx:addLoadoutItem`, `esx:removeLoadoutItem`) and updates the client-side data accordingly. This feature is only enabled when `ESX.GetConfig("CustomInventory")` is false, maintaining compatibility with custom inventory systems.
---
The changes are necessary to maintain consistency between server-side inventory/loadout state and the client's `ESX.PlayerData`. As of now, you have to use `ESX.GetPlayerData()` just to get an updated state of the inventory. And the loadout is out of sync regardless.
---
- Listens to secure net events:
- `esx:addInventoryItem`
- …
> feat: sync player data inv & loadout

- [core]/esx_identity/server/main.lua
- [core]/esx_skin/server/main.lua
> use static player methods

- [core]/es_extended/imports.lua
- [core]/es_extended/server/classes/player.lua
- [core]/es_extended/server/functions.lua
Adds `ESX.ExtendedPlayers` as a lightweight wrapper for `ESX.GetExtendedPlayers`. Returns tables of `StaticPlayer` objects (method-only wrappers) for multiple players, following the same pattern as the existing `ESX.Player` function.
---
`ESX.Player` provides a minimal interface for a single player by exposing only methods via `StaticPlayer`. This reduces bloat and avoids exposing full `xPlayer` properties. `ESX.ExtendedPlayers` extends this approach to multiple players, making it easier to work with groups of players while keeping the same clean, method-only interface.
---
- Introduces `StaticPlayer` class.
- Implements `ESX.ExtendedPlayers(key?, val?)` which:
- Returns an array of `StaticPlayer` objects for a single filter.
- Returns a table mapping groups to arrays of `StaticPlayer` …
> feat(es_extended): add static ESX.ExtendedPlayers

- [core]/es_extended/fxmanifest.lua
- [core]/es_extended/server/functions.lua
- [core]/es_extended/server/migration/main.lua
- [core]/es_extended/server/migration/v1.13.3/ssn/main.lua
Introduces a migration system for ESX that allows adding database migrations for older versions.  
Includes a new migration for v1.13.3 that adds a unique `ssn` column to the `users` table, backfills existing users, and ensures the column is `NOT NULL`.  
---
Previously, migrating users between ESX versions required manual SQL updates and ad-hoc scripts, which was error-prone and time-consuming.  
This new system standardizes migrations, allows safe execution, and can be extended to handle migrations for any older ESX version.
---
- Migrations are registered in a `Migrations` table keyed by ESX version.
- Each migration is a Lua function that executes SQL updates and any necessary data transformations.
- The runner iterates through all migrations for a given version and executes them.
- …
> feat: add auto-migrations on startup
